"""Versioned, profile-driven PDF extraction shared by research consumers."""

from .adapters import (
    IsolatedNativeAdapter,
    PaddleOcrAdapter,
    PdfInspectorNativeAdapter,
    PdfInspectorOcrAdapter,
)
from .native_worker import NATIVE_WORKER_PROTOCOL, NativeWorkerPool, get_shared_native_worker_pool
from .core import (
    DEFAULT_MODE_BUDGETS,
    PDF_PARSER_SCHEMA_VERSION,
    PdfCandidate,
    PdfDiagnostic,
    PdfDocumentResult,
    PdfOcrMode,
    PdfPageCacheBackend,
    PdfPageResult,
    PdfParseRequest,
    PdfProfile,
    PdfRecoveryPolicy,
    PdfResourceLimits,
    PdfRouter,
    PdfiumNativeAdapter,
    PypdfNativeAdapter,
    compute_content_hash,
    detect_text_quality,
)
from .evaluation import (
    MANDATORY_600036_CASE,
    PdfAcceptanceGates,
    PdfEvaluationCase,
    assess_gpu_canary,
    assess_report,
    benchmark_native_parallelism,
    build_archive_manifest,
    evaluate_cases,
    load_manifest,
    probe_ocr_components,
    run_bounded_canary,
    stratify_cases,
    write_report,
)
from .profiles import (
    DEFAULT_PROFILES,
    build_router,
    profile_from_mapping,
    resolve_profile,
)

__all__ = [
    "PDF_PARSER_SCHEMA_VERSION",
    "DEFAULT_MODE_BUDGETS",
    "PdfCandidate",
    "PdfDiagnostic",
    "PdfDocumentResult",
    "PdfPageResult",
    "PdfParseRequest",
    "PdfProfile",
    "PdfResourceLimits",
    "PdfPageCacheBackend",
    "PdfOcrMode",
    "PdfRecoveryPolicy",
    "PdfRouter",
    "PdfiumNativeAdapter",
    "PypdfNativeAdapter",
    "compute_content_hash",
    "detect_text_quality",
    "PaddleOcrAdapter",
    "IsolatedNativeAdapter",
    "NativeWorkerPool",
    "get_shared_native_worker_pool",
    "NATIVE_WORKER_PROTOCOL",
    "PdfInspectorNativeAdapter",
    "PdfInspectorOcrAdapter",
    "DEFAULT_PROFILES",
    "profile_from_mapping",
    "build_router",
    "resolve_profile",
    "PdfEvaluationCase",
    "PdfAcceptanceGates",
    "load_manifest",
    "build_archive_manifest",
    "stratify_cases",
    "evaluate_cases",
    "run_bounded_canary",
    "probe_ocr_components",
    "assess_report",
    "assess_gpu_canary",
    "benchmark_native_parallelism",
    "write_report",
    "MANDATORY_600036_CASE",
]
