"""Versioned, profile-driven PDF extraction shared by research consumers."""

from .core import (
    PDF_PARSER_SCHEMA_VERSION,
    DEFAULT_MODE_BUDGETS,
    PdfCandidate,
    PdfDiagnostic,
    PdfDocumentResult,
    PdfPageResult,
    PdfParseRequest,
    PdfProfile,
    PdfResourceLimits,
    PdfPageCacheBackend,
    PdfOcrMode,
    PdfRecoveryPolicy,
    PdfRouter,
    PypdfNativeAdapter,
    compute_content_hash,
    detect_text_quality,
)
from .adapters import PaddleOcrAdapter, PdfInspectorNativeAdapter, PdfInspectorOcrAdapter
from .profiles import DEFAULT_PROFILES, build_router, profile_from_mapping, resolve_profile
from .evaluation import MANDATORY_600036_CASE, PdfAcceptanceGates, PdfEvaluationCase, assess_report, build_archive_manifest, evaluate_cases, load_manifest, probe_ocr_components, run_bounded_canary, stratify_cases, write_report

__all__ = [
    "PDF_PARSER_SCHEMA_VERSION",
    "DEFAULT_MODE_BUDGETS",
    "PdfCandidate",
    "PdfDiagnostic",
    "PdfDocumentResult",
    "PdfPageResult",
    "PdfParseRequest",
    "PdfProfile",
    "PdfResourceLimits",
    "PdfPageCacheBackend",
    "PdfOcrMode",
    "PdfRecoveryPolicy",
    "PdfRouter",
    "PypdfNativeAdapter",
    "compute_content_hash",
    "detect_text_quality",
    "PaddleOcrAdapter",
    "PdfInspectorNativeAdapter",
    "PdfInspectorOcrAdapter",
    "DEFAULT_PROFILES",
    "profile_from_mapping",
    "build_router",
    "resolve_profile",
    "PdfEvaluationCase",
    "PdfAcceptanceGates",
    "load_manifest",
    "build_archive_manifest",
    "stratify_cases",
    "evaluate_cases",
    "run_bounded_canary",
    "probe_ocr_components",
    "assess_report",
    "write_report",
    "MANDATORY_600036_CASE",
]
